# Site settings
title: Learning JRubyArt
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Here I will write about JRubyArt.
baseurl: "" # the subpath of your site, e.g. /blog/
regenerate: true
urls:
  bugs: http://github.com/ruby-processing/jruby_art/issues
  wiki: https://github.com/ruby-processing/JRubyArt/wiki
  github: https://github.com/monkstone.io
twitter_username: monkstoneT
github_username:  monkstone
syntax-highlighting:
    enabled: true
# Build settings
kramdown:
  highlighter: rouge
  input: GFM
gems: 
  - jekyll-sitemap
